// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    SvgIcon: typeof import('./components/svg/SvgIcon.vue')['default']
  }
}

export { }
